# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests for sFastIcon iOS App"
  lane :generate_rls_ipa do
    build_app(
      get_certificates,           # invokes cert
      get_provisioning_profile,   # invokes sigh
      export_xcargs: "-allowProvisioningUpdates",
      scheme: "sFastIconUnitTests",
      include_bitcode: true
    )
  end

  lane :generate_dev_ipa do
    build_app(
      scheme: "sFastIcon",
      include_bitcode: true
    )
  end

  desc "Run unit tests for sFastIcon iOS App"
  lane :test_ios_pra do
    run_tests(
      devices: ["iPhone 8"],
      scheme: "sFastIconUnitTests"
    )
  end

  desc "Run simulator tests for sFastIcon iOS App"
  lane :test_ios_qe do
    run_tests(
      devices: ["iPhone 8"],
      scheme: "sFastIconUITests"
    )
  end

  desc "Generate new localized screenshots for sFastIcon"
  lane :screenshots do
    capture_screenshots(
      devices: ["iPhone 8"],
      scheme: "sFastIconUITests"
    )
  end

  desc "Run Danger for PRA Commit to Repo Comments"
  lane :ios_danger do
    danger(
      use_bundle_exec: true,
      verbose: true,
      danger_id: "sfasticon_ios_dangerfile",
      new_comment: false,
      dangerfile: "fastlane/ios_dangerfile"
    )
  end
end
