#!/usr/bin/env groovy
#
#   Fastfile
#   sImageViewer
#   Created by Duncan Wallace 08/21/2020
#   Copyright © 2020. Duncwa LLC.  All rights reserved


default_platform(:ios)

platform :ios do
  desc "Run unit tests for sFastIcon iOS App"
  lane :generate_rls_ipa do
    build_app(
      codesigning_identity: "Apple Distribution",
      clean: true,
      scheme: "sFastIcon",
      configuration: "Release",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.dw4workonly.fastimage" => "DIS_SwiftImageViewer"
        }
      },
      include_bitcode: true,
      include_symbols: true
    )
  end

  lane :generate_dev_ipa do
    build_app(
      codesigning_identity: "Apple Development",
      clean: true,
      scheme: "sFastIcon",
      configuration: "Debug",
      export_options: {
        method: "development",
        provisioningProfiles: {
          "com.dw4workonly.fastimage" => "DEV_SwiftImageViewer"
        }
      },
      include_bitcode: false,
      include_symbols: true

    )
  end

  desc "Run unit tests for sFastIcon iOS App"
  lane :test_ios_pra do
    run_tests(
      device: "iPhone 8",
      scheme: "sFastIconUnitTests",
      code_coverage: true,
      output_directory: "fastlane/test_output",
      formatter: "xcpretty-json-formatter"
    )
  end

  desc "Run simulator tests for sFastIcon iOS App"
  lane :test_ios_qe do
    run_tests(
      device: "iPhone 8",
      scheme: "sFastIconUITests",
      code_coverage: true,
      output_directory: "fastlane/test_output",
      formatter: "xcpretty-json-formatter"
    )
  end

  desc "Run simulator tests for sFastIcon iOS App"
  lane :run_ios_ins do
    build_app(
      codesigning_identity: "Apple Development",
      clean: true,
      scheme: "sFastIcon",
      configuration: "Debug",
      export_options: {
        method: "development",
        provisioningProfiles: {
          "com.dw4workonly.fastimage" => "DEV_SwiftImageViewer"
        }
      },
      include_bitcode: false
    )
    ## Call inspection bulkextractor on *.ipa file
    sh 'echo "Running Bulkextractor inspection"'
  end


  desc "Generate new localized screenshots for sFastIcon"
  lane :screenshots do
    capture_screenshots(
      devices: ["iPhone 8"],
      scheme: "sFastIconUITests"
    )
  end

  desc "Run Danger for PRA Commit to Repo Comments"
  lane :ios_danger do
    # sh 'bundle exec danger pr https://github.com/duncwa/sImageViewer/pull/2 --dangerfile=fastlane/ios_dangerfile'
    # danger(
    #   use_bundle_exec: true,
    #   verbose: true,
    #   danger_id: "sfasticon_ios_dangerfile",
    #   new_comment: false,
    #   dangerfile: "fastlane/ios_dangerfile"
    # )
    sh 'bundle exec danger --dangerfile=fastlane/ios_dangerfile'

  end
end
